package com.tcl.routes;

import org.apache.camel.builder.RouteBuilder;

public class ProductLimitSkipAndSelectedFieldFE extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        onException(Exception.class, java.net.ConnectException.class)
                .useOriginalMessage()
                .handled(true)
                .log("\n\n\n\n In exception block ${exception.getClass().getCanonicalName()}  and ${exception.message}\n\n\n\n")
                .removeHeader("org.restlet.http.headers")
                .setProperty("ErrorOccured", constant("yes"))
                .setProperty("ExpMsg", simple("${exception.message}"))
                .setProperty("stacktrace", simple("${exception.stacktrace}"))
                .setHeader("exceptionName", simple("${exception.getClass().getCanonicalName()}"))
                .setBody(simple("{\"retStatus\": \"ERROR\", \"errorMessage\" : \"${exchangeProperty.ExpMsg}\"}"))
                .convertBodyTo(String.class)
                .process("ResponseProcessor")
                .setHeader("Content-Type", constant("application/json"))
                .setHeader("TransactionId", simple("${exchangeProperty.TransactionId}"))
                .setHeader("ConversationID", simple("${exchangeProperty.ConversationID}"))
                .setHeader("ProcessName", simple("${exchangeProperty.ProcessName}"))
                .setProperty("targetSystem", simple("${header.SourceName}"))
                .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                .setProperty("MessageType", constant("SourceResponse"))
                .setHeader("responseStatus", constant("Failure"))
                .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                .wireTap("seda:loggerprocess");

        from("direct:limitskipandselectedfield")
                .setProperty("ProcessName", simple("{{route.productLimitSkipAndSelectedField_ProcessName}}"))
                .setProperty("ServiceName", simple("{{route.ServiceName}}"))
                .setProperty("MaskFields", simple("{{route.productLimitSkipAndSelectedField_MaskFields}}"))
                .setProperty("TransactionId", simple("${exchangeId}"))
                .setProperty("ConversationID", simple("${header.ConversationID}"))
                .setProperty("authorization", simple("${header.Authorization}"))
                .setProperty("SourceName", simple("${header.SourceName}"))
                .setProperty("targetSystem", simple("BACKEND_ADAPTER"))
                .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                .setProperty("MessageType", simple("SourceRequest"))
                .setHeader("ProcessName", simple("${exchangeProperty.ProcessName}"))
                .setHeader("TransactionId", simple("${exchangeProperty.TransactionId}"))
                .setProperty("OriginalRequest", simple("${body}"))
                .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                .wireTap("seda:loggerprocess")
                .to("direct:processHeader")
                .choice()
                    .when(simple("${header.MissingHeader} == 'MissingHeader'"))
                        .setProperty("MessageType", simple("SourceResponse"))
                        .setProperty("targetSystem", simple("${in.header.SourceName}"))
                        .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                        .setHeader("CamelHttpResponseCode", simple("400"))
                        .setHeader("responseStatus", simple("Failure"))
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .wireTap("seda:loggerprocess")
                    .endChoice()
                    .otherwise()
                        .setBody(simple("${exchangeProperty.OriginalRequest}"))
                        .convertBodyTo(String.class)
                        .setProperty("MessageType", simple("BERequest"))
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .wireTap("seda:loggerprocess")
						.log("USER_FE:: Before calling target url")
                        .to("{{route.productLimitSkipAndSelectedField_BEAdapterEndpoint}}")
						.log("USER_FE:: After calling target url ${body}")
                        .setHeader("Content-Type", simple("application/json"))
                        .convertBodyTo(String.class)
                        .setProperty("MessageType", simple("BEResponse"))
                        .setProperty("targetSystem", simple("BACKEND_ADAPTER"))
                        .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .wireTap("seda:loggerprocess")
                        .setProperty("productLimitSkipAndSelectedField_Body", simple("${body}"))
                        .setProperty("ErrorOccured", constant("no"))
                        .log("USER_FE_001:: Response code is ${header.CamelHttpResponseCode}")
                        .process("ResponseProcessor")
                        .log("USER_FE_002:: Response code is ${header.CamelHttpResponseCode} || ErrorOccured : ${exchangeProperty.ErrorOccured}")
                        .setProperty("MessageType", simple("SourceResponse"))
                        .setProperty("targetSystem", simple("${header.SourceName}"))
                        .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                        .convertBodyTo(String.class)
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .wireTap("seda:loggerprocess");
    }
}
