package com.tcl.routes;

import org.apache.camel.builder.RouteBuilder;

public class SearchProductFE extends RouteBuilder {
    @Override
    public void configure() throws Exception {

        onException(Exception.class)
                .useOriginalMessage()
                .handled(true)
                .removeHeader("org.restlet.http.headers")
                .setProperty("ErrorOccured", constant("yes"))
                .setProperty("ExpMsg", simple("${exception.message}"))
                .bean("RemoveNewLinesFromExpMsgAndName", "removeNewLinesFromExpMsg")
                .setProperty("stacktrace", simple("${exception.stacktrace}"))
                .setHeader("exceptionName", simple("${exception.getClass().getCanonicalName()}"))
                .bean("RemoveNewLinesFromExpMsgAndName", "removeNewLinesFromExpName")
                .setBody(simple("{\"retStatus\": \"ERROR\", \"errorMessage\" : \"${exchangeProperty.ExpMsg}\"}"))
                .convertBodyTo(String.class)
                .process("ResponseProcessor")
                .setHeader("Content-Type", constant("application/json"))
                .setHeader("TransactionId", simple("${exchangeProperty.TransactionId}"))
                .setHeader("ConversationID", simple("${exchangeProperty.ConversationID}"))
                .setHeader("ProcessName", simple("${exchangeProperty.ProcessName}"))
                .setProperty("targetSystem", simple("${header.SourceName}"))
                .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                .setProperty("MessageType", simple("SourceResponse"))
                .setHeader("responseStatus", constant("Failure"))
                .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                .wireTap("seda:loggerprocess")
                .removeHeaders("*", "(?i)Content-Type|(?i)CamelHttpResponseCode|(?i)ConversationId|(?i)transactionId|(?i)responseStatus|(?i)statusMessage|(?i)sysErrorCode|(?i)sysErrorMessage");


        from("direct:searchproduct")
                .setProperty("ProcessName", simple("{{route.searchProduct_ProcessName}}"))
                .setProperty("ServiceName", simple("{{route.ServiceName}}"))
                .setProperty("MaskFields", simple("{{route.searchProduct_MaskFields}}"))
                .setProperty("TransactionId", simple("${exchangeId}"))
                .setProperty("ConversationID", simple("${header.ConversationID}"))
                .setProperty("authorization", simple("${header.Authorization}"))
                .setProperty("SourceName", simple("${header.SourceName}"))
                .setProperty("targetSystem", simple("BACKEND_ADAPTER"))
                .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                .setProperty("MessageType", simple("SourceRequest"))
                .setHeader("ProcessName", simple("${exchangeProperty.ProcessName}"))
                .setHeader("TransactionId", simple("${exchangeProperty.TransactionId}"))
                .setProperty("OriginalRequest", simple("${body}"))
                .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                .wireTap("seda:loggerprocess")
                .to("direct:processHeader")
                .choice()
                    .when(simple("${header.MissingHeader} == 'MissingHeader'"))
                        .setProperty("MessageType", simple("SourceResponse"))
                        .setProperty("targetSystem", simple("${in.header.SourceName}"))
                        .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                        .setHeader("CamelHttpResponseCode", simple("400"))
                        .setHeader("responseStatus", simple("Failure"))
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .wireTap("seda:loggerprocess")
                        .removeHeaders("MissingHeader|ProcessName|responseStatus")
                    .endChoice()
                    .otherwise()
                        .setBody(simple("${exchangeProperty.OriginalRequest}"))
                        .convertBodyTo(String.class)
                        .setProperty("MessageType", simple("BERequest"))
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .removeHeaders("*", "(?i)transactionId|(?i)ConversationID|(?i)SourceName")
                        .wireTap("seda:loggerprocess")
                        .to("{{route.searchProduct_BEAdapterEndpoint}}")
                        .convertBodyTo(String.class)
                        .setProperty("MessageType", simple("BEResponse"))
                        .setProperty("targetSystem", simple("BACKEND_ADAPTER"))
                        .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                        .removeHeader("(?i)Responsestatus")
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .wireTap("seda:loggerprocess")
                        .setProperty("searchProduct_Body", simple("${body}"))
                        .setProperty("ErrorOccured", constant("no"))
                        .process("ResponseProcessor")
                        .setProperty("MessageType", simple("SourceResponse"))
                        .setProperty("targetSystem", simple("${header.SourceName}"))
                        .setHeader("targetSystem", simple("${exchangeProperty.targetSystem}"))
                        .convertBodyTo(String.class)
                        .setProperty("CurrentTimestamp", simple("${date-with-timezone:now:IST:dd-MMM-yyyy HH:mm:ss.SSS}"))
                        .removeHeaders("*", "(?i)Content-Type|(?i)CamelHttpResponseCode|(?i)ConversationId|(?i)transactionId|(?i)responseStatus|(?i)statusMessage|(?i)sysErrorCode|(?i)sysErrorMessage")
                        .wireTap("seda:loggerprocess")
                    .endChoice();
    }
}
